spring：
  profiles：
    active: configserver
  application:
    name: configserver
  cloud:
    config:
      server:
        accept-empty: false
        git:
          uri: httpsgithub.com535431135config.git
          skip-ssl-validation: true
          timeout: 5

  config:
    name: configserver
server:
  port: 9999